
name: Test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2']
        gemfile:
          - Gemfile

    runs-on: ubuntu-20.04
    continue-on-error: false

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
    - uses: actions/checkout@v3

    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake
